services:
  - type: web
    name: aaj-kya-banaoon
    env: node
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ..
      npm install
    startCommand: node dist/index.js
    rootDir: .
