"""
Dataset for meal suggestions based on various features
"""

# Sample meal dataset with features
MEAL_DATASET = [
    {
        "id": "1",
        "name": "Masala Dosa",
        "description": "Crispy rice crepes with spiced potato filling, served with chutney and sambar",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 30,
        "calories": 250,
        "protein": 6,
        "carbs": 45,
        "fat": 5,
        "tags": ["Light", "Balanced", "Quick"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["rice flour", "urad dal", "potatoes", "onions", "mustard seeds", "curry leaves", "green chilies"]
    },
    {
        "id": "2",
        "name": "Chole Bhature",
        "description": "Spicy chickpea curry served with deep-fried bread",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 60,
        "calories": 650,
        "protein": 18,
        "carbs": 85,
        "fat": 28,
        "tags": ["Spicy", "Protein", "Festive"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["chickpeas", "tomatoes", "onions", "spices", "flour", "yogurt"]
    },
    {
        "id": "3",
        "name": "Idli Sambar",
        "description": "Steamed rice cakes served with lentil stew and coconut chutney",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 45,
        "calories": 220,
        "protein": 8,
        "carbs": 40,
        "fat": 3,
        "tags": ["Healthy", "Light", "Probiotic"],
        "suitable_for": ["Morning"],
        "ingredients": ["rice", "urad dal", "fenugreek seeds", "dal", "vegetables", "tamarind"]
    },
    {
        "id": "4",
        "name": "Paneer Butter Masala",
        "description": "Cottage cheese cubes in a rich, creamy tomato sauce",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 40,
        "calories": 450,
        "protein": 16,
        "carbs": 20,
        "fat": 35,
        "tags": ["Protein", "Spicy", "Balanced"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["paneer", "tomatoes", "cream", "butter", "spices", "cashews"]
    },
    {
        "id": "5",
        "name": "Aloo Paratha",
        "description": "Whole wheat flatbread stuffed with spiced potatoes",
        "meal_type": "breakfast",
        "region": "North India",
        "preparation_time": 40,
        "calories": 350,
        "protein": 8,
        "carbs": 60,
        "fat": 12,
        "tags": ["Quick", "One-pot", "Balanced"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["wheat flour", "potatoes", "onions", "spices", "ghee"]
    },
    {
        "id": "6",
        "name": "Palak Paneer",
        "description": "Cottage cheese in a creamy spinach gravy",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 35,
        "calories": 320,
        "protein": 14,
        "carbs": 15,
        "fat": 25,
        "tags": ["Healthy", "Protein", "Balanced"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["spinach", "paneer", "onions", "tomatoes", "spices", "cream"]
    },
    {
        "id": "7",
        "name": "Samosa",
        "description": "Crispy pastry filled with spiced potatoes and peas",
        "meal_type": "snack",
        "region": "North India",
        "preparation_time": 50,
        "calories": 250,
        "protein": 4,
        "carbs": 30,
        "fat": 14,
        "tags": ["Spicy", "Quick", "One-pot"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["flour", "potatoes", "peas", "spices", "oil"]
    },
    {
        "id": "8",
        "name": "Biryani",
        "description": "Fragrant rice dish with meat or vegetables and aromatic spices",
        "meal_type": "lunch",
        "region": "Hyderabad",
        "preparation_time": 90,
        "calories": 550,
        "protein": 20,
        "carbs": 70,
        "fat": 20,
        "tags": ["Festive", "Spicy", "Balanced"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["basmati rice", "meat/vegetables", "onions", "yogurt", "spices", "herbs"]
    },
    {
        "id": "9",
        "name": "Pav Bhaji",
        "description": "Spiced vegetable mash served with buttered bread rolls",
        "meal_type": "dinner",
        "region": "Maharashtra",
        "preparation_time": 30,
        "calories": 400,
        "protein": 8,
        "carbs": 60,
        "fat": 15,
        "tags": ["Quick", "Spicy", "One-pot"],
        "suitable_for": ["Evening"],
        "ingredients": ["mixed vegetables", "potatoes", "tomatoes", "spices", "butter", "bread rolls"]
    },
    {
        "id": "10",
        "name": "Poha",
        "description": "Flattened rice with spices, nuts, and vegetables",
        "meal_type": "breakfast",
        "region": "Central India",
        "preparation_time": 20,
        "calories": 250,
        "protein": 5,
        "carbs": 45,
        "fat": 7,
        "tags": ["Quick", "Light", "Healthy"],
        "suitable_for": ["Morning"],
        "ingredients": ["flattened rice", "onions", "peanuts", "spices", "curry leaves"]
    },
    {
        "id": "11",
        "name": "Dhokla",
        "description": "Steamed savory cake made from fermented batter",
        "meal_type": "snack",
        "region": "Gujarat",
        "preparation_time": 40,
        "calories": 180,
        "protein": 6,
        "carbs": 30,
        "fat": 5,
        "tags": ["Healthy", "Light", "Probiotic"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["rice", "chickpea flour", "yogurt", "mustard seeds", "curry leaves", "green chilies"]
    },
    {
        "id": "12",
        "name": "Butter Chicken",
        "description": "Tender chicken in a rich, creamy tomato sauce",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 50,
        "calories": 550,
        "protein": 30,
        "carbs": 15,
        "fat": 40,
        "tags": ["Protein", "Spicy", "Festive"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["chicken", "tomatoes", "cream", "butter", "spices", "cashews"]
    },
    {
        "id": "13",
        "name": "Rasam",
        "description": "Tangy, spicy soup with tamarind and spices",
        "meal_type": "lunch",
        "region": "South India",
        "preparation_time": 25,
        "calories": 120,
        "protein": 3,
        "carbs": 20,
        "fat": 4,
        "tags": ["Healthy", "Light", "Quick"],
        "suitable_for": ["Afternoon"],
        "ingredients": ["tamarind", "tomatoes", "spices", "curry leaves", "mustard seeds"]
    },
    {
        "id": "14",
        "name": "Malai Kofta",
        "description": "Vegetable and cheese dumplings in a creamy sauce",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 60,
        "calories": 480,
        "protein": 10,
        "carbs": 40,
        "fat": 30,
        "tags": ["Festive", "Balanced"],
        "suitable_for": ["Evening"],
        "ingredients": ["potatoes", "paneer", "vegetables", "cream", "spices", "nuts"]
    },
    {
        "id": "15",
        "name": "Upma",
        "description": "Savory semolina porridge with vegetables and spices",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 25,
        "calories": 220,
        "protein": 5,
        "carbs": 40,
        "fat": 6,
        "tags": ["Quick", "Light", "One-pot"],
        "suitable_for": ["Morning"],
        "ingredients": ["semolina", "vegetables", "mustard seeds", "curry leaves", "ghee"]
    },
    {
        "id": "16",
        "name": "Rajma Chawal",
        "description": "Kidney bean curry served with steamed rice",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 60,
        "calories": 400,
        "protein": 15,
        "carbs": 70,
        "fat": 8,
        "tags": ["Protein", "Balanced", "One-pot"],
        "suitable_for": ["Afternoon"],
        "ingredients": ["kidney beans", "rice", "onions", "tomatoes", "spices"]
    },
    {
        "id": "17",
        "name": "Medu Vada",
        "description": "Savory lentil donuts served with coconut chutney and sambar",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 45,
        "calories": 280,
        "protein": 10,
        "carbs": 35,
        "fat": 12,
        "tags": ["Protein", "Spicy"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["urad dal", "rice flour", "onions", "spices", "curry leaves"]
    },
    {
        "id": "18",
        "name": "Dal Tadka",
        "description": "Yellow lentils tempered with spices and herbs",
        "meal_type": "dinner",
        "region": "All India",
        "preparation_time": 30,
        "calories": 220,
        "protein": 12,
        "carbs": 30,
        "fat": 7,
        "tags": ["Protein", "Healthy", "One-pot"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["lentils", "tomatoes", "onions", "spices", "ghee", "garlic"]
    },
    {
        "id": "19",
        "name": "Jalebi",
        "description": "Deep-fried sweet pretzel soaked in sugar syrup",
        "meal_type": "dessert",
        "region": "All India",
        "preparation_time": 40,
        "calories": 350,
        "protein": 2,
        "carbs": 75,
        "fat": 10,
        "tags": ["Festive", "Sweet"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["flour", "sugar", "saffron", "cardamom", "oil"]
    },
    {
        "id": "20",
        "name": "Chana Masala",
        "description": "Spiced chickpea curry with onions and tomatoes",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 35,
        "calories": 320,
        "protein": 15,
        "carbs": 45,
        "fat": 10,
        "tags": ["Protein", "Spicy", "One-pot"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["chickpeas", "onions", "tomatoes", "spices", "herbs"]
    },
    {
        "id": "21",
        "name": "Mysore Pak",
        "description": "Traditional sweet made with gram flour, ghee, and sugar",
        "meal_type": "dessert",
        "region": "South India",
        "preparation_time": 30,
        "calories": 400,
        "protein": 4,
        "carbs": 60,
        "fat": 20,
        "tags": ["Festive", "Sweet"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["gram flour", "ghee", "sugar", "cardamom"]
    },
    {
        "id": "22",
        "name": "Khichdi",
        "description": "One-pot dish of rice and lentils with mild spices",
        "meal_type": "dinner",
        "region": "All India",
        "preparation_time": 30,
        "calories": 300,
        "protein": 12,
        "carbs": 50,
        "fat": 8,
        "tags": ["Healthy", "One-pot", "Light"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["rice", "lentils", "vegetables", "spices", "ghee"]
    },
    {
        "id": "23",
        "name": "Aloo Gobi",
        "description": "Potato and cauliflower curry with spices",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 35,
        "calories": 250,
        "protein": 6,
        "carbs": 40,
        "fat": 10,
        "tags": ["One-pot", "Balanced", "Quick"],
        "suitable_for": ["Evening"],
        "ingredients": ["potatoes", "cauliflower", "onions", "tomatoes", "spices"]
    },
    {
        "id": "24",
        "name": "Pakoras",
        "description": "Deep-fried vegetable fritters with chickpea flour batter",
        "meal_type": "snack",
        "region": "All India",
        "preparation_time": 25,
        "calories": 280,
        "protein": 5,
        "carbs": 25,
        "fat": 18,
        "tags": ["Quick", "Spicy"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["gram flour", "vegetables", "spices", "oil"]
    },
    {
        "id": "25",
        "name": "Gajar Ka Halwa",
        "description": "Sweet carrot pudding with milk, nuts, and ghee",
        "meal_type": "dessert",
        "region": "North India",
        "preparation_time": 50,
        "calories": 400,
        "protein": 7,
        "carbs": 55,
        "fat": 20,
        "tags": ["Festive", "Sweet"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["carrots", "milk", "sugar", "ghee", "nuts", "cardamom"]
    },
    {
        "id": "26",
        "name": "Bhindi Masala",
        "description": "Okra stir-fried with onions, tomatoes, and spices",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 30,
        "calories": 180,
        "protein": 4,
        "carbs": 20,
        "fat": 12,
        "tags": ["Healthy", "Quick", "Light"],
        "suitable_for": ["Afternoon"],
        "ingredients": ["okra", "onions", "tomatoes", "spices", "oil"]
    },
    {
        "id": "27",
        "name": "Kathi Roll",
        "description": "Flatbread wrap with spiced fillings and chutneys",
        "meal_type": "snack",
        "region": "East India",
        "preparation_time": 35,
        "calories": 450,
        "protein": 18,
        "carbs": 40,
        "fat": 25,
        "tags": ["Quick", "Spicy", "Protein"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["flatbread", "fillings", "onions", "spices", "chutneys"]
    },
    {
        "id": "28",
        "name": "Rogan Josh",
        "description": "Aromatic lamb curry with rich spices",
        "meal_type": "dinner",
        "region": "Kashmir",
        "preparation_time": 90,
        "calories": 580,
        "protein": 35,
        "carbs": 10,
        "fat": 45,
        "tags": ["Spicy", "Protein", "Festive"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["lamb", "onions", "tomatoes", "yogurt", "spices"]
    },
    {
        "id": "29",
        "name": "Matar Paneer",
        "description": "Cottage cheese and peas in a tomato-based gravy",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 40,
        "calories": 380,
        "protein": 14,
        "carbs": 20,
        "fat": 30,
        "tags": ["Protein", "Balanced", "Quick"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["paneer", "peas", "onions", "tomatoes", "spices"]
    },
    {
        "id": "30",
        "name": "Gulab Jamun",
        "description": "Deep-fried milk solids soaked in sugar syrup",
        "meal_type": "dessert",
        "region": "All India",
        "preparation_time": 45,
        "calories": 420,
        "protein": 5,
        "carbs": 70,
        "fat": 15,
        "tags": ["Festive", "Sweet"],
        "suitable_for": ["Afternoon", "Evening", "Night"],
        "ingredients": ["milk powder", "flour", "sugar", "cardamom", "saffron", "nuts"]
    }
]

# Festival specific dishes
FESTIVAL_DISHES = {
    "diwali": ["Gulab Jamun", "Jalebi", "Mysore Pak", "Gajar Ka Halwa", "Samosa", "Chole Bhature"],
    "holi": ["Gujiya", "Puran Poli", "Dahi Bhalla", "Thandai", "Pakoras"],
    "navratri": ["Sabudana Khichdi", "Kuttu Ki Puri", "Singhare Ka Halwa", "Makhana Kheer", "Aloo Jeera"],
    "eid": ["Biryani", "Sheer Khurma", "Seviyan", "Kebabs", "Haleem"],
    "pongal": ["Pongal Rice", "Vadai", "Payasam", "Avial", "Sakkarai Pongal"],
    "onam": ["Avial", "Sambar", "Parippu", "Olan", "Payasam"],
    "durga_puja": ["Mishti Doi", "Kosha Mangsho", "Luchi", "Cholar Dal", "Sandesh"],
    "ganesh_chaturthi": ["Modak", "Puran Poli", "Karanji", "Sheera", "Ladoo"],
    "bihu": ["Pitha", "Laru", "Khar", "Masor Tenga", "Jolpan"],
    "guru_nanak_jayanti": ["Kada Prasad", "Langar", "Amritsari Kulcha", "Pinni", "Maa Di Dal"],
    "chhath_puja": ["Thekua", "Kheer", "Rasiao Kheer", "Kaddu Bhaat", "Chana Dal"],
    "janmashtami": ["Panjiri", "Makhan Mishri", "Dahi Mishri", "Panchamrit", "Kheer"],
    "raksha_bandhan": ["Kaju Katli", "Barfi", "Ladoo", "Kheer", "Gulab Jamun"],
    "karwa_chauth": ["Pheni", "Sargi", "Matthi", "Meethi Sevaiyan", "Dry Fruits"],
    "baisakhi": ["Kada Prasad", "Chole Bhature", "Lassi", "Pindi Chole", "Amritsari Kulcha"]
}

# Function to get meal suggestions based on time of day
def get_meals_by_time(time_of_day, limit=5):
    """Get meal suggestions based on time of day"""
    suitable_meals = [meal for meal in MEAL_DATASET if time_of_day in meal["suitable_for"]]
    return suitable_meals[:limit]

# Function to get meal suggestions based on tags
def get_meals_by_tags(tags, limit=5):
    """Get meal suggestions based on tags"""
    suitable_meals = []
    for meal in MEAL_DATASET:
        if any(tag in meal["tags"] for tag in tags):
            suitable_meals.append(meal)
    return suitable_meals[:limit]

# Function to get festival-specific dishes
def get_festival_dishes(festival_id, limit=5):
    """Get dishes for a specific festival"""
    if festival_id.lower() in FESTIVAL_DISHES:
        dishes = FESTIVAL_DISHES[festival_id.lower()]
        return [meal for meal in MEAL_DATASET if meal["name"] in dishes][:limit]
    return []