"""
Dataset for meal suggestions based on various features
"""

# Convert dataset to standardized format
def standardize_meal_dataset(dataset):
    """
    Standardizes the meal dataset by ensuring 'suitable_for' and 'ingredients' are always lists
    and converts all entries to a consistent format
    """
    for meal in dataset:
        # Convert suitable_for to list if it's a string
        if isinstance(meal.get('suitable_for'), str):
            # Split by semicolon or comma, depending on what's in the string
            if ';' in meal['suitable_for']:
                meal['suitable_for'] = [item.strip() for item in meal['suitable_for'].split(';')]
            else:
                meal['suitable_for'] = [item.strip() for item in meal['suitable_for'].split(',')]
        
        # Convert ingredients to list if it's a string
        if isinstance(meal.get('ingredients'), str):
            # Split by semicolon or comma, depending on what's in the string
            if ';' in meal['ingredients']:
                meal['ingredients'] = [item.strip() for item in meal['ingredients'].split(';')]
            else:
                meal['ingredients'] = [item.strip() for item in meal['ingredients'].split(',')]
        
        # Convert tags to list if it's a string
        if isinstance(meal.get('tags'), str):
            meal['tags'] = [item.strip() for item in meal['tags'].split(',')]
        
        # Convert id to string format consistently for all entries
        if isinstance(meal.get('id'), int):
            meal['id'] = str(meal['id'])
    
    return dataset

# Sample meal dataset with features
_MEAL_DATASET_RAW = [
 {
   "id": "1",
   "name": "Balu shahi",
   "description": "Traditional Indian sweet made with maida flour and yogurt",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 70,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "Quick", "One-pot", "Diwali_Special", "Raksha_Bandhan_Sweet"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Maida flour", "yogurt", "oil", "sugar"],
   "imageUrl": "https://source.unsplash.com/400x300/?balu-shahi"
 },
 {
   "id": "2",
   "name": "Boondi",
   "description": "Sweet fried gram flour pearls in syrup",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 110,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "Quick", "One-pot", "Diwali_Special", "Holi_Celebration"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Gram flour", "ghee", "sugar"],
   "imageUrl": "/Indian Food Images/boondi/8e98a5a8c0.jpg"
 },
 {
   "id": "3",
   "name": "Gajar ka halwa",
   "description": "Carrot pudding with milk and nuts",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 75,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Healthy", "Festive", "One-pot", "Diwali_Special", "Karwa_Chauth_Special"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Carrots", "milk", "sugar", "ghee", "cashews", "raisins"],
   "imageUrl": "/Indian Food Images/gajar_ka_halwa/9f54710edb.jpg"
 },
 {
   "id": "4",
   "name": "Ghevar",
   "description": "Honeycomb-like sweet with ghee and nuts",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "One-pot", "Raksha_Bandhan_Sweet"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Flour", "ghee", "kewra", "milk", "clarified butter", "sugar", "almonds", "pistachio", "saffron", "green cardamom"],
   "imageUrl": "/Indian Food Images/ghevar/9fb15bda28.jpg"
 },
 {
   "id": "5",
   "name": "Gulab jamun",
   "description": "Milk-based fried balls in rose syrup",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 55,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "Quick", "One-pot", "Diwali_Special", "Eid_Feast", "Raksha_Bandhan_Sweet"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Milk powder", "plain flour", "baking powder", "ghee", "milk", "sugar", "water", "rose water"],
   "imageUrl": "/Indian Food Images/gulab_jamun/9c70d9a3ff.jpg"
 },
 {
   "id": 6,
   "name": "Imarti",
   "description": "Lentil flour rings soaked in syrup",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Sugar syrup; lentil flour",
   "imageUrl": "/Indian Food Images/imarti/9e403f98a5.jpg"
 },
 {
   "id": 7,
   "name": "Jalebi",
   "description": "Crispy spirals soaked in sugar syrup",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Quick", "One-pot", "Diwali_Special", "Holi_Celebration", "Eid_Feast", "Raksha_Bandhan_Sweet", "Baisakhi_Special"],
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Maida; corn flour; baking soda; vinegar; curd; water; turmeric; saffron; cardamom",
   "imageUrl": "/Indian Food Images/jalebi/ff8e19229e.jpg"
 },
 {
   "id": 8,
   "name": "Kaju katli",
   "description": "Cashew fudge with cardamom",
   "meal_type": "dessert",
   "region": "Unknown",
   "preparation_time": 30,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Quick", "One-pot", "Diwali_Special", "Raksha_Bandhan_Sweet"],
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Cashews; ghee; cardamom; sugar"
 },
 {
   "id": 9,
   "name": "Kalakand",
   "description": "Milk and cottage cheese sweet",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Milk; cottage cheese; sugar",
   "imageUrl": "/Indian Food Images/kalakand/9e2e1b3a38.jpg"
 },
 {
   "id": 10,
   "name": "Kheer",
   "description": "Rice pudding with milk and dried fruits",
   "meal_type": "dessert",
   "region": "Unknown",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["One-pot", "Diwali_Special", "Navratri_Dish", "Eid_Feast", "Durga_Puja_Sweet", "Chhath_Puja_Offering", "Janmashtami_Special", "Raksha_Bandhan_Sweet", "Karwa_Chauth_Special"],
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Milk; rice; sugar; dried fruits"
 },
 {
   "id": 11,
   "name": "Laddu",
   "description": "Sweet gram flour balls",
   "meal_type": "dessert",
   "region": "Unknown",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Gram flour; ghee; sugar"
 },
 {
   "id": 12,
   "name": "Lassi",
   "description": "Sweet yogurt drink with nuts",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 10,
   "calories": 200,
   "protein": 5,
   "carbs": 30,
   "fat": 8,
   "tags": "Probiotic,Healthy,Quick",
   "suitable_for": "Morning;Afternoon",
   "ingredients": "Yogurt; milk; nuts; sugar",
   "imageUrl": "/Indian Food Images/lassi/9e5f542316.jpg"
 },
 {
   "id": 13,
   "name": "Nankhatai",
   "description": "Indian shortbread cookies",
   "meal_type": "dessert",
   "region": "Unknown",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Refined flour; besan; ghee; powdered sugar; yoghurt; green cardamom"
 },
 {
   "id": 14,
   "name": "Petha",
   "description": "Candied pumpkin sweet",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 40,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Firm white pumpkin; sugar; kitchen lime; alum powder"
 },
 {
   "id": 15,
   "name": "Phirni",
   "description": "Rice pudding with nuts",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice; sugar; nuts",
   "imageUrl": "/Indian Food Images/phirni/9fe5d747bf.jpg"
 },
 {
   "id": 16,
   "name": "Rabri",
   "description": "Thickened sweetened milk with spices",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 55,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Condensed milk; sugar; spices; nuts",
   "imageUrl": "/Indian Food Images/rabri/9c7feeacfa.jpg"
 },
 {
   "id": 17,
   "name": "Sheera",
   "description": "Semolina pudding with nuts",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 35,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Semolina; ghee; nuts; milk",
   "imageUrl": "/Indian Food Images/sheera/9f115c78c4.jpg"
 },
 {
   "id": 18,
   "name": "Singori",
   "description": "Leaf-wrapped khoa and coconut sweet",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 30,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Khoa; coconut; molu leaf"
 },
 {
   "id": 19,
   "name": "Sohan halwa",
   "description": "Corn flour and dry fruit fudge",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 70,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Corn flour; ghee; dry fruits",
   "imageUrl": "/Indian Food Images/sohan_halwa/ffa15e9afb.jpg"
 },
 {
   "id": 20,
   "name": "Sohan papdi",
   "description": "Flaky gram flour sweet",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Gram flour; ghee; sugar; milk; cardamom",
   "imageUrl": "/Indian Food Images/sohan_papdi/abc322a381.jpg"
 },
 {
   "id": 21,
   "name": "Chhena jalebi",
   "description": "Chhena cheese rings in syrup",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chhena; sugar; ghee",
   "imageUrl": "/Indian Food Images/jalebi/ff8e19229e.jpg"
 },
 {
   "id": 22,
   "name": "Chhena kheeri",
   "description": "Chhena cheese in sweet milk",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chhena; sugar; milk",
   "imageUrl": "/Indian Food Images/chhena_kheeri/9eb1ac0483.jpg"
 },
 {
   "id": 23,
   "name": "Chhena poda",
   "description": "Baked chhena cheese sweet",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 55,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Sugar; chenna cheese"
 },
 {
   "id": 24,
   "name": "Cham cham",
   "description": "Cream-filled sweet rolls",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 100,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Flour; cream; sugar; saffron; lemon juice; coconut flakes",
   "imageUrl": "/Indian Food Images/cham_cham/9a16393e6c.jpg"
 },
 {
   "id": 25,
   "name": "Kheer sagar",
   "description": "Chenna balls in condensed milk",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 85,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chenna; condensed milk; sugar; saffron; cardamom",
   "imageUrl": "/Indian Food Images/chak_hao_kheer/9f380a0f74.jpg"
 },
 {
   "id": 26,
   "name": "Ledikeni",
   "description": "Chhena cheese fried sweets",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 90,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chhena; sugar; ghee",
   "imageUrl": "/Indian Food Images/ledikeni/9b174098ab.jpg"
 },
 {
   "id": 27,
   "name": "Lyangcha",
   "description": "Fried milk flour sweets in syrup",
   "meal_type": "dessert",
   "region": "North East India",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Flour; fried milk power; sugar syrup",
   "imageUrl": "/Indian Food Images/lyangcha/9d93106e71.jpg"
 },
 {
   "id": 28,
   "name": "Malapua",
   "description": "Sweet pancakes with fennel",
   "meal_type": "dessert",
   "region": "North India",
   "preparation_time": 130,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Yoghurt; refined flour; ghee; fennel seeds",
   "imageUrl": "/Indian Food Images/malapua/fdefa50c5b.jpg"
 },
 {
   "id": 29,
   "name": "Mihidana",
   "description": "Tiny sweet gram flour pearls",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Besan flour; sugar; ghee"
 },
 {
   "id": 30,
   "name": "Misti doi",
   "description": "Sweet yogurt with jaggery",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 510,
   "calories": 200,
   "protein": 5,
   "carbs": 30,
   "fat": 8,
   "tags": "Probiotic,Healthy,Quick",
   "suitable_for": "Morning;Afternoon",
   "ingredients": "Milk; jaggery",
   "imageUrl": "/Indian Food Images/misti_doi/9f6ce9165e.jpg"
 },
 {
   "id": 31,
   "name": "Pantua",
   "description": "Fried chhena balls in syrup",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 90,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chhena; sugar; ghee; flour"
 },
 {
   "id": 32,
   "name": "Pithe",
   "description": "Stuffed rice flour dumplings",
   "meal_type": "dessert",
   "region": "North East India",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; wheat flour",
   "imageUrl": "/Indian Food Images/pithe/9f849ef5c6.jpg"
 },
 {
   "id": 33,
   "name": "Rasabali",
   "description": "Chenna in sweetened milk",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chenna; sweetened milk"
 },
 {
   "id": 34,
   "name": "Ras malai",
   "description": "Chhena balls in reduced milk",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 240,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chhena; reduced milk; pistachio",
   "imageUrl": "/Indian Food Images/ras_malai/9f2e04d1e6.jpg"
 },
 {
   "id": 35,
   "name": "Rasgulla",
   "description": "Spongy chhena balls in syrup",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 100,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chhena; sugar; cardamom",
   "imageUrl": "/Indian Food Images/rasgulla/9edcc97fc8.jpg"
 },
 {
   "id": 36,
   "name": "Sandesh",
   "description": "Soft chhena sweet with spices",
   "meal_type": "dessert",
   "region": "East India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chenna; cardamom; pistachios",
   "imageUrl": "/Indian Food Images/sandesh/7eab0972a1.jpg"
 },
 {
   "id": 37,
   "name": "Adhirasam",
   "description": "Rice flour and jaggery sweet discs",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; jaggery; cardamom; sesame seeds",
   "imageUrl": "/Indian Food Images/adhirasam/9fb6ec6325.jpg"
 },
 {
   "id": 38,
   "name": "Ariselu",
   "description": "Rice flour and jaggery discs",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; jaggery; ghee",
   "imageUrl": "/Indian Food Images/ariselu/9fd8707b08.jpg"
 },
 {
   "id": 39,
   "name": "Bandar laddu",
   "description": "Besan, coconut and ghee sweets",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Gram flour; coconut; ghee; sugar",
   "imageUrl": "/Indian Food Images/bandarladdu/9b8d97dd20.jpg"
 },
 {
   "id": 40,
   "name": "Chikki",
   "description": "Peanut and jaggery sweet bars",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 30,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Peanuts; jaggery",
   "imageUrl": "/Indian Food Images/chikki/9f4a64fb09.jpg"
 },
 {
   "id": 41,
   "name": "Double ka meetha",
   "description": "Fried bread in sweet cream",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 50,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Bread; ghee; sugar; milk; saffron",
   "imageUrl": "/Indian Food Images/double_ka_meetha/9e7d6d776d.jpg"
 },
 {
   "id": 42,
   "name": "Gavvalu",
   "description": "Crunchy rice flour sweets",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; ghee; sugar; spices",
   "imageUrl": "/Indian Food Images/gavvalu/9fa35b2436.jpg"
 },
 {
   "id": 43,
   "name": "Kakinada khaja",
   "description": "Layered wheat flour sweet",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Wheat flour; ghee; sugar",
   "imageUrl": "/Indian Food Images/kakinada_khaja/9ec10dc5f5.jpg"
 },
 {
   "id": 44,
   "name": "Dharwad pedha",
   "description": "Sweet milk discs with saffron",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 230,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Milk; sugar; saffron",
   "imageUrl": "/Indian Food Images/dharwad_pedha/9c4cd63c9a.jpg"
 },
 {
   "id": 45,
   "name": "Anarsa",
   "description": "Rice flour, sugar and spice sweet",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 90,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; sugar; spices",
   "imageUrl": "/Indian Food Images/anarsa/9fba3d6a83.jpg"
 },
 {
   "id": 46,
   "name": "Mysore pak",
   "description": "Gram flour and ghee dessert",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Gram flour (besan); ghee; sugar",
   "imageUrl": "/Indian Food Images/mysorepak/0abf2d644a.jpg"
 },
 {
   "id": 47,
   "name": "Obbattu holige",
   "description": "Stuffed flatbread with coconut and jaggery",
   "meal_type": "main course",
   "region": "South India",
   "preparation_time": 240,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": ["Festive", "One-pot", "Holi_Celebration", "Ganesh_Chaturthi_Sweet"],
   "suitable_for": ["Afternoon", "Evening", "Night"],
   "ingredients": ["Maida flour", "turmeric", "coconut", "chickpeas", "jaggery", "ghee", "cardamom"]
 },
 {
   "id": 48,
   "name": "Palathalikalu",
   "description": "Rice flour dumplings in milk",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 35,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; milk"
 },
 {
   "id": 49,
   "name": "Poornalu",
   "description": "Stuffed rice flour balls with chana dal and jaggery",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 300,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chana dal; jaggery"
 },
 {
   "id": 50,
   "name": "Pongal",
   "description": "Sweet rice with jaggery and cashews",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 25,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "Quick", "One-pot", "Pongal_Harvest"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Rice", "jaggery", "cashews", "ghee"]
 },
 {
   "id": 51,
   "name": "Pootharekulu",
   "description": "Rice paper sheets with sugar filling",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 90,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice starch; sugar; ghee",
   "imageUrl": "/Indian Food Images/pootharekulu/9f50481e75.jpg"
 },
 {
   "id": 52,
   "name": "Qubani ka meetha",
   "description": "Apricot dessert with sugar syrup",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 30,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Apricots; sugar syrup",
   "imageUrl": "/Indian Food Images/qubani_ka_meetha/9ea6c9779e.jpg"
 },
 {
   "id": 53,
   "name": "Sheer korma",
   "description": "Vermicelli pudding with milk",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 30,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "One-pot", "Eid_Feast"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Vermicelli pudding", "milk"],
   "imageUrl": "/Indian Food Images/sheer_korma/9e7fb4be48.jpg"
 },
 {
   "id": 54,
   "name": "Unni Appam",
   "description": "Fried banana and rice flour dumplings",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 35,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice; jaggery; banana; coconut",
   "imageUrl": "/Indian Food Images/unni_appam/9c69b761b4.jpg"
 },
 {
   "id": 55,
   "name": "Kajjikaya",
   "description": "Coconut and jaggery filled pastry",
   "meal_type": "dessert",
   "region": "South India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Maida flour; coconut; jaggery",
   "imageUrl": "/Indian Food Images/kajjikaya/9e68562649.jpg"
 },
 {
   "id": 56,
   "name": "Anarsa",
   "description": "Rice flour sweet with poppy seeds",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rice flour; jaggery; khus-khus seeds",
   "imageUrl": "/Indian Food Images/anarsa/9fba3d6a83.jpg"
 },
 {
   "id": 57,
   "name": "Basundi",
   "description": "Thickened sweet milk with nuts",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Sugar; milk; nuts",
   "imageUrl": "/Indian Food Images/basundi/9e5e83dc2b.jpg"
 },
 {
   "id": 58,
   "name": "Dhondas",
   "description": "Cucumber and rava sweet",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 60,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Cucumber; rava",
   "imageUrl": "/Indian Food Images/dhondas/9f8e16fb10.jpg"
 },
 {
   "id": 59,
   "name": "Doodhpak",
   "description": "Rice pudding with dry fruits",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 70,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Milk; rice; sugar; dry fruits",
   "imageUrl": "/Indian Food Images/doodhpak/9e85e0b1be.jpg"
 },
 {
   "id": 60,
   "name": "Mahim halwa",
   "description": "Semolina and sugar sweet",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 35,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Semolina; sugar",
   "imageUrl": "/Indian Food Images/mahim_halwa/9f8e16fb10.jpg"
 },
 {
   "id": 61,
   "name": "Modak",
   "description": "Steamed rice flour dumplings with coconut and jaggery",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 25,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "Quick", "One-pot", "Ganesh_Chaturthi_Sweet"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Rice flour", "coconut", "jaggery"],
   "imageUrl": "/Indian Food Images/modak/9f63c374e0.jpg"
 },
 {
   "id": 62,
   "name": "Shankarpali",
   "description": "Sweet fried flour and semolina snacks",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 45,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Sugar; ghee; maida flour; semolina",
   "imageUrl": "/Indian Food Images/shankarpali/9fdb8fb617.jpg"
 },
 {
   "id": 63,
   "name": "Shrikhand",
   "description": "Sweet strained yogurt with saffron",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 730,
   "calories": 200,
   "protein": 5,
   "carbs": 30,
   "fat": 8,
   "tags": "Probiotic,Healthy,Quick",
   "suitable_for": "Morning;Afternoon",
   "ingredients": "Curd; sugar; saffron; cardamom",
   "imageUrl": "/Indian Food Images/shrikhand/8ff6eab553.jpg"
 },
 {
   "id": 64,
   "name": "Sutar feni",
   "description": "Flaky sweet with maida and ghee",
   "meal_type": "dessert",
   "region": "West India",
   "preparation_time": 70,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Maida; sugar; ghee",
   "imageUrl": "/Indian Food Images/sutar_feni/9c91e3356d.jpg"
 },
 {
   "id": 65,
   "name": "Maach Jhol",
   "description": "Fish curry with vegetables",
   "meal_type": "main course",
   "region": "North East India",
   "preparation_time": 50,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Spicy,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Fish; potol; tomato; chillies; ginger; garlic",
   "imageUrl": "/Indian Food Images/maach_jhol/9e28bb5f8f.jpg"
 },
 {
   "id": 66,
   "name": "Pork Bharta",
   "description": "Spicy pork mash with onions",
   "meal_type": "main course",
   "region": "North East India",
   "preparation_time": -1,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Spicy,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Boiled pork; onions; chillies; ginger; garlic",
   "imageUrl": "/Indian Food Images/pork_bharta/9f8e16fb10.jpg"
 },
 {
   "id": 67,
   "name": "Chak Hao Kheer",
   "description": "Black rice pudding",
   "meal_type": "dessert",
   "region": "North East India",
   "preparation_time": 285,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": ["Festive", "One-pot", "Bihu_Special", "Durga_Puja_Sweet"],
   "suitable_for": ["Afternoon", "Evening"],
   "ingredients": ["Rice", "milk", "sugar", "cardamom"],
   "imageUrl": "/Indian Food Images/chak_hao_kheer/9f380a0f74.jpg"
 },
 {
   "id": 68,
   "name": "Galho",
   "description": "Rice and pork stew with axone",
   "meal_type": "main course",
   "region": "North East India",
   "preparation_time": 20,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Spicy,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Rice; axone; salt; water; chillies; pork",
   "imageUrl": "/Indian Food Images/galho/9f8e16fb10.jpg"
 },
 {
   "id": 69,
   "name": "Aloo gobi",
   "description": "Cauliflower and potato curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 30,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Cauliflower; potato; garam masala; turmeric; curry leaves",
   "imageUrl": "/Indian Food Images/aloogobi/9e42364d56.jpg"
 },
 {
   "id": 70,
   "name": "Aloo tikki",
   "description": "Potato patties with spices",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 25,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Rice flour; potato; bread crumbs; garam masala; salt",
   "imageUrl": "/Indian Food Images/alootikki/9f5b0916d7.jpg"
 },
 {
   "id": 71,
   "name": "Aloo matar",
   "description": "Potato and pea curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 45,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Potato; peas; chillies; ginger; garam masala; garlic",
   "imageUrl": "/Indian Food Images/aloo_matar/9f8e16fb10.jpg"
 },
 {
   "id": 72,
   "name": "Aloo methi",
   "description": "Potato and fenugreek curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 50,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Potato; fenugreek leaves; chillies; salt; oil",
   "imageUrl": "/Indian Food Images/aloomethi/9f3551eeff.jpg"
 },
 {
   "id": 73,
   "name": "Aloo shimla mirch",
   "description": "Potato and capsicum curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 50,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Potato; shimla mirch; garam masala; amchur powder; salt",
   "imageUrl": "/Indian Food Images/alooshimlamirch/9fef927573.jpg"
 },
 {
   "id": 74,
   "name": "Bhatura",
   "description": "Fried bread with chickpea curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 40,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Chole; rava; yogurt; plain flour; baking soda",
   "imageUrl": "/Indian Food Images/bhatura/0e84306e25.jpg"
 },
 {
   "id": 75,
   "name": "Bhindi masala",
   "description": "Okra stir-fried with spices",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 50,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Ladies finger; garam masala; kasuri methi; tomatoes; chili powder",
   "imageUrl": "/Indian Food Images/bhindimasala/9f2f3cf0e4.jpg"
 },
 {
   "id": 76,
   "name": "Biryani",
   "description": "Spiced rice with chicken and aromatics",
   "meal_type": "main course",
   "region": "South India",
   "preparation_time": 150,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": ["Festive", "Protein", "One-pot", "Eid_Feast"],
   "suitable_for": ["Afternoon", "Evening", "Night"],
   "ingredients": ["Chicken thighs", "basmati rice", "star anise", "sweet", "green chillies"],
   "imageUrl": "/Indian Food Images/biryani/9c42c23e69.jpg"
 },
 {
   "id": 77,
   "name": "Butter chicken",
   "description": "Creamy tomato chicken curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 45,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Chicken; greek yogurt; cream; garam masala powder; cashew nuts; butter",
   "imageUrl": "/Indian Food Images/butter_chicken/9ad6c9413f.jpg"
 },
 {
   "id": 78,
   "name": "Chana masala",
   "description": "Spicy chickpea curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 50,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Protein,Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Chickpeas; tomato paste; garam masala; ginger; red onion; avocado oil",
   "imageUrl": "/Indian Food Images/chanamasala/9f8e16fb10.jpg"
 },
 {
   "id": 79,
   "name": "Chapati",
   "description": "Whole wheat flatbread",
   "meal_type": "main course",
   "region": "West India",
   "preparation_time": 20,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Whole wheat flour; olive oil; hot water; all purpose flour",
   "imageUrl": "/Indian Food Images/chapati/9e68842803.jpg"
 },
 {
   "id": 80,
   "name": "Chicken razala",
   "description": "Chicken curry with yogurt and nuts",
   "meal_type": "main course",
   "region": "East India",
   "preparation_time": 45,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Chicken; dahi; sesame seeds; garam masala powder; cashew nuts; saffron",
   "imageUrl": "/Indian Food Images/chicken_razala/9f1bea68a0.jpg"
 },
 {
   "id": 81,
   "name": "Chicken Tikka masala",
   "description": "Chicken in creamy tomato sauce",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 60,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Naan bread; tomato sauce; skinless chicken breasts; heavy cream; garam masala",
   "imageUrl": "/Indian Food Images/chicken_tikka_masala/9fcb2f58ab.jpg"
 },
 {
   "id": 82,
   "name": "Chicken Tikka",
   "description": "Grilled spiced chicken",
   "meal_type": "starter",
   "region": "North India",
   "preparation_time": 165,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,Quick",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Chicken; whole wheat bread; rice flour; garam masala powder; whole egg",
   "imageUrl": "/Indian Food Images/chickentikka/9f8e16fb10.jpg"
 },
 {
   "id": 83,
   "name": "Chole bhature",
   "description": "Tangy chickpeas with deep-fried bread",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 70,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": ["Festive", "One-pot", "Punjabi_Special"],
   "suitable_for": ["Afternoon", "Evening", "Night"],
   "ingredients": ["Chole", "bhatura", "garam masala", "bay leaf", "cinnamon stick"],
   "imageUrl": "/Indian Food Images/bhatura/0e84306e25.jpg"
 },
 {
   "id": 84,
   "name": "Daal baati churma",
   "description": "Lentil curry with wheat dumplings",
   "meal_type": "main course",
   "region": "West India",
   "preparation_time": 100,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Moong dal; masoor dal; chana dal; wheat flour; almond",
   "imageUrl": "/Indian Food Images/daal_baati_churma/9e95461988.jpg"
 },
 {
   "id": 85,
   "name": "Daal puri",
   "description": "Stuffed lentil bread",
   "meal_type": "main course",
   "region": "East India",
   "preparation_time": 60,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Moong dal; garam masala powder; garlic; green chilli; all purpose flour",
   "imageUrl": "/Indian Food Images/daal_puri/9e9dc7cd20.jpg"
 },
 {
   "id": 86,
   "name": "Dal makhani",
   "description": "Creamy black lentil curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 70,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,Protein,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Red kidney beans; urad dal; cream; garam masala; chili powder",
   "imageUrl": "/Indian Food Images/dal_makhani/9f24729196.jpg"          
 },
 {
   "id": 87,
   "name": "Dal tadka",
   "description": "Yellow lentils tempered with spices",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 40,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Protein,Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Pigeon peas; garam masala; ginger; red onion; kasuri methi",
   "imageUrl": "/Indian Food Images/dal_tadka/9ef5584bb1.jpg"
 },
 {
   "id": 88,
   "name": "Dum aloo",
   "description": "Spicy baby potato curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 70,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Baby potatoes; garam masala; cashew nuts; kasuri methi; tomatoes",
   "imageUrl": "/Indian Food Images/dum_aloo/9ee1e2da6e.jpg"
 },
 {
   "id": 89,
   "name": "Poha",
   "description": "Flattened rice with potatoes and spices",
   "meal_type": "snack",
   "region": "West India",
   "preparation_time": 50,
   "calories": 200,
   "protein": 5,
   "carbs": 30,
   "fat": 8,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Morning;Afternoon",
   "ingredients": "Beaten rice flakes; potato; curry leaves; green chilies; lemon juice",
   "imageUrl": "/Indian Food Images/poha/9dd3b41182.jpg"
 },
 {
   "id": 90,
   "name": "Fara",
   "description": "Steamed lentil dumplings",
   "meal_type": "snack",
   "region": "Central India",
   "preparation_time": 70,
   "calories": 200,
   "protein": 5,
   "carbs": 30,
   "fat": 8,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Morning;Afternoon",
   "ingredients": "Chana dal; whole wheat flour; arhar dal; white urad dal; garam masala powder",
   "imageUrl": "/Indian Food Images/fara/9f8e16fb10.jpg"
 },
 {
   "id": 91,
   "name": "Kachori",
   "description": "Deep-fried bread with spicy filling",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 40,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Festive,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Urud dal; moong dal; all purpose flour; fennel seeds; ginger",
   "imageUrl": "/Indian Food Images/kachori/9f8c9e23cf.jpg"
 },
 {
   "id": 92,
   "name": "Kadai paneer",
   "description": "Paneer and bell pepper curry",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 50,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Protein,Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Cottage cheese; bell peppers; gravy; garam masala; cashew nuts",
   "imageUrl": "/Indian Food Images/kadai_paneer/9fd537dd7c.jpg"
 },
 {
   "id": 93,
   "name": "Kadhi pakoda",
   "description": "Gram flour dumplings in spiced yogurt sauce",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 70,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Protein,Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Besan; garam masala powder; gram flour; ginger; curry leaves",
   "imageUrl": "/Indian Food Images/kadhi_pakoda/9edebebe19.jpg"
 },
 {
   "id": 94,
   "name": "Karela bharta",
   "description": "Bitter gourd mash with spices",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 70,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": "Healthy,Quick,One-pot",
   "suitable_for": "Afternoon;Evening;Night",
   "ingredients": "Bitter gourd; fennel; garam masala powder; chili powder; amchur powder",
   "imageUrl": "/Indian Food Images/karela_bharta/9e9737b337.jpg"
 },
 {
   "id": 95,
   "name": "Paneer butter masala",
   "description": "Cheese cubes in rich tomato gravy",
   "meal_type": "main course",
   "region": "North India",
   "preparation_time": 40,
   "calories": 350,
   "protein": 8,
   "carbs": 40,
   "fat": 15,
   "tags": ["Protein", "One-pot", "Punjabi_Delicacy", "North_Indian_Favorite"],
   "suitable_for": ["Afternoon", "Evening", "Night"],
   "ingredients": ["Paneer", "Tomato", "Butter", "Cream", "Onion", "Spices"],
   "imageUrl": "/Indian Food Images/paneerbuttermasala/9fe7856ec3.jpg"
 },
 {
   "id": 96,
   "name": "Kulfi falooda",
   "description": "Frozen milk dessert with vermicelli",
   "meal_type": "dessert",
   "region": "Unknown",
   "preparation_time": 70,
   "calories": 250,
   "protein": 4,
   "carbs": 35,
   "fat": 10,
   "tags": "Festive,Quick,One-pot",
   "suitable_for": "Afternoon;Evening",
   "ingredients": "Rose syrup; falooda sev; mixed nuts; saffron; sugar",
   "imageUrl": "/Indian Food Images/kulfi_falooda/9f8e16fb10.jpg"
 },
    {
        "id": "98",
        "name": "Masala Dosa",
        "description": "Crispy rice crepes with spiced potato filling, served with chutney and sambar",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 30,
        "calories": 250,
        "protein": 6,
        "carbs": 45,
        "fat": 5,
        "tags": ["Light", "Balanced", "Quick"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["rice flour", "urad dal", "potatoes", "onions", "mustard seeds", "curry leaves", "green chilies"],
        "imageUrl": "/Indian Food Images/masaladosa/9f8e16fb10.jpg"
    },
    {
        "id": "99",
        "name": "Chole Bhature",
        "description": "Spicy chickpea curry served with deep-fried bread",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 60,
        "calories": 650,
        "protein": 18,
        "carbs": 85,
        "fat": 28,
        "tags": ["Spicy", "Protein", "Festive", "Baisakhi_Special", "Guru_Nanak_Jayanti_Food"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["chickpeas", "tomatoes", "onions", "spices", "flour", "yogurt"],
        "imageUrl": "/Indian Food Images/cholebhature/9f8e16fb10.jpg"
    },
    {
        "id": "100",
        "name": "Idli Sambar",
        "description": "Steamed rice cakes served with lentil stew and coconut chutney",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 45,
        "calories": 220,
        "protein": 8,
        "carbs": 40,
        "fat": 3,
        "tags": ["Healthy", "Light", "Probiotic", "Onam_Sadhya_Dish"],
        "suitable_for": ["Morning"],
        "ingredients": ["rice", "urad dal", "fenugreek seeds", "dal", "vegetables", "tamarind"],
        "imageUrl": "/Indian Food Images/idlisambar/9f8e16fb10.jpg"
    },
    {
        "id": "101",
        "name": "Paneer Butter Masala",
        "description": "Cottage cheese cubes in a rich, creamy tomato sauce",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 40,
        "calories": 450,
        "protein": 16,
        "carbs": 20,
        "fat": 35,
        "tags": ["Protein", "Spicy", "Balanced"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["paneer", "tomatoes", "cream", "butter", "spices", "cashews"],
        "imageUrl": "/Indian Food Images/paneerbuttermasala/9f8e16fb10.jpg"
    },
    {
        "id": "102",
        "name": "Aloo Paratha",
        "description": "Whole wheat flatbread stuffed with spiced potatoes",
        "meal_type": "breakfast",
        "region": "North India",
        "preparation_time": 40,
        "calories": 350,
        "protein": 8,
        "carbs": 60,
        "fat": 12,
        "tags": ["Quick", "One-pot", "Balanced"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["wheat flour", "potatoes", "onions", "spices", "ghee"],
        "imageUrl": "/Indian Food Images/alooparatha/9f8e16fb10.jpg"
    },
    {
        "id": "103",
        "name": "Palak Paneer",
        "description": "Cottage cheese in a creamy spinach gravy",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 35,
        "calories": 320,
        "protein": 14,
        "carbs": 15,
        "fat": 25,
        "tags": ["Healthy", "Protein", "Balanced"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["spinach", "paneer", "onions", "tomatoes", "spices", "cream"],
        "imageUrl": "/Indian Food Images/palakpaneer/9e19735fc3.jpg"
    },
    {
        "id": "104",
        "name": "Samosa",
        "description": "Crispy pastry filled with spiced potatoes and peas",
        "meal_type": "snack",
        "region": "North India",
        "preparation_time": 50,
        "calories": 250,
        "protein": 4,
        "carbs": 30,
        "fat": 14,
        "tags": ["Spicy", "Quick", "One-pot", "Diwali_Special", "Holi_Celebration"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["flour", "potatoes", "peas", "spices", "oil"],
        "imageUrl": "/Indian Food Images/samosa/9f8e16fb10.jpg"
    },
    {
        "id": "105",
        "name": "Hyderabadi Biryani",
        "description": "Fragrant rice dish with meat or vegetables and aromatic spices",
        "meal_type": "lunch",
        "region": "Hyderabad",
        "preparation_time": 90,
        "calories": 550,
        "protein": 20,
        "carbs": 70,
        "fat": 20,
        "tags": ["Festive", "Spicy", "Balanced", "Eid_Feast"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["basmati rice", "meat/vegetables", "onions", "yogurt", "spices", "herbs"],
        "imageUrl": "/Indian Food Images/hyderabadi_biryani/9f8e16fb10.jpg"
    },
    {
        "id": "106",
        "name": "Pav Bhaji",
        "description": "Spiced vegetable mash served with buttered bread rolls",
        "meal_type": "dinner",
        "region": "Maharashtra",
        "preparation_time": 30,
        "calories": 400,
        "protein": 8,
        "carbs": 60,
        "fat": 15,
        "tags": ["Quick", "Spicy", "One-pot"],
        "suitable_for": ["Evening"],
        "ingredients": ["mixed vegetables", "potatoes", "tomatoes", "spices", "butter", "bread rolls"],
        "imageUrl": "/Indian Food Images/pav_bhaji/9f8e16fb10.jpg"
    },
    {
        "id": "107",
        "name": "Indori Poha",
        "description": "Flattened rice with spices, nuts, and vegetables",
        "meal_type": "breakfast",
        "region": "Central India",
        "preparation_time": 20,
        "calories": 250,
        "protein": 5,
        "carbs": 45,
        "fat": 7,
        "tags": ["Quick", "Light", "Healthy"],
        "suitable_for": ["Morning"],
        "ingredients": ["flattened rice", "onions", "peanuts", "spices", "curry leaves"],
        "imageUrl": "/Indian Food Images/indori_poha/9f8e16fb10.jpg"
    },
    {
        "id": "108",
        "name": "Dhokla",
        "description": "Steamed savory cake made from fermented batter",
        "meal_type": "snack",
        "region": "Gujarat",
        "preparation_time": 40,
        "calories": 180,
        "protein": 6,
        "carbs": 30,
        "fat": 5,
        "tags": ["Healthy", "Light", "Probiotic"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["rice", "chickpea flour", "yogurt", "mustard seeds", "curry leaves", "green chilies"],
        "imageUrl": "/Indian Food Images/dhokla/9f8e16fb10.jpg"
    },
    {
        "id": "109",
        "name": "Butter Chicken",
        "description": "Tender chicken in a rich, creamy tomato sauce",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 50,
        "calories": 550,
        "protein": 30,
        "carbs": 15,
        "fat": 40,
        "tags": ["Protein", "Spicy", "Festive"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["chicken", "tomatoes", "cream", "butter", "spices", "cashews"],
        "imageUrl": "/Indian Food Images/butter_chicken/9e0ea4e35d.jpg"
    },
    {
        "id": "110",
        "name": "Rasam",
        "description": "Tangy, spicy soup with tamarind and spices",
        "meal_type": "lunch",
        "region": "South India",
        "preparation_time": 25,
        "calories": 120,
        "protein": 3,
        "carbs": 20,
        "fat": 4,
        "tags": ["Healthy", "Light", "Quick"],
        "suitable_for": ["Afternoon"],
        "ingredients": ["tamarind", "tomatoes", "spices", "curry leaves", "mustard seeds"],
        "imageUrl": "/Indian Food Images/rasam/9f8e16fb10.jpg"
    },
    {
        "id": "111",
        "name": "Malai Kofta",
        "description": "Vegetable and cheese dumplings in a creamy sauce",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 60,
        "calories": 480,
        "protein": 10,
        "carbs": 40,
        "fat": 30,
        "tags": ["Festive", "Balanced"],
        "suitable_for": ["Evening"],
        "ingredients": ["potatoes", "paneer", "vegetables", "cream", "spices", "nuts"],
        "imageUrl": "/Indian Food Images/malai_kofta/9f8e16fb10.jpg"
    },
    {
        "id": "112",
        "name": "Upma",
        "description": "Savory semolina porridge with vegetables and spices",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 25,
        "calories": 220,
        "protein": 5,
        "carbs": 40,
        "fat": 6,
        "tags": ["Quick", "Light", "One-pot"],
        "suitable_for": ["Morning"],
        "ingredients": ["semolina", "vegetables", "mustard seeds", "curry leaves", "ghee"],
        "imageUrl": "/Indian Food Images/upma/9f8e16fb10.jpg"
    },
    {
        "id": "113",
        "name": "Rajma Chawal",
        "description": "Kidney bean curry served with steamed rice",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 60,
        "calories": 400,
        "protein": 15,
        "carbs": 70,
        "fat": 8,
        "tags": ["Protein", "Balanced", "One-pot"],
        "suitable_for": ["Afternoon"],
        "ingredients": ["kidney beans", "rice", "onions", "tomatoes", "spices"],
        "imageUrl": "/Indian Food Images/rajma_chawal/9f07700000.jpg"
    },
    {
        "id": "114",
        "name": "Medu Vada",
        "description": "Savory lentil donuts served with coconut chutney and sambar",
        "meal_type": "breakfast",
        "region": "South India",
        "preparation_time": 45,
        "calories": 280,
        "protein": 10,
        "carbs": 35,
        "fat": 12,
        "tags": ["Protein", "Spicy"],
        "suitable_for": ["Morning", "Afternoon"],
        "ingredients": ["urad dal", "rice flour", "onions", "spices", "curry leaves"],
        "imageUrl": "/Indian Food Images/medu_vada/9f8e16fb10.jpg"
    },
    {
        "id": "115",
        "name": "Dal Tadka",
        "description": "Yellow lentils tempered with spices and herbs",
        "meal_type": "dinner",
        "region": "All India",
        "preparation_time": 30,
        "calories": 220,
        "protein": 12,
        "carbs": 30,
        "fat": 7,
        "tags": ["Protein", "Healthy", "One-pot"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["lentils", "tomatoes", "onions", "spices", "ghee", "garlic"],
        "imageUrl": "/Indian Food Images/dal_tadka/9c8f6aeb0a.jpg"
    },
    {
        "id": "116",
        "name": "Fresh Jalebi",
        "description": "Deep-fried sweet pretzel soaked in sugar syrup",
        "meal_type": "dessert",
        "region": "All India",
        "preparation_time": 40,
        "calories": 350,
        "protein": 2,
        "carbs": 75,
        "fat": 10,
        "tags": ["Festive", "Sweet", "Diwali_Special", "Holi_Celebration", "Baisakhi_Special"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["flour", "sugar", "saffron", "cardamom", "oil"],
        "imageUrl": "/Indian Food Images/jalebi/ff8e19229e.jpg"
    },
    {
        "id": "117",
        "name": "Chana Masala",
        "description": "Spiced chickpea curry with onions and tomatoes",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 35,
        "calories": 320,
        "protein": 15,
        "carbs": 45,
        "fat": 10,
        "tags": ["Protein", "Spicy", "One-pot"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["chickpeas", "onions", "tomatoes", "spices", "herbs"],
        "imageUrl": "/Indian Food Images/chana_masala/9f8e16fb10.jpg"
    },
    {
        "id": "118",
        "name": "Mysore Pak",
        "description": "Traditional sweet made with gram flour, ghee, and sugar",
        "meal_type": "dessert",
        "region": "South India",
        "preparation_time": 30,
        "calories": 400,
        "protein": 4,
        "carbs": 60,
        "fat": 20,
        "tags": ["Festive", "Sweet"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["gram flour", "ghee", "sugar", "cardamom"],
        "imageUrl": "/Indian Food Images/mysore_pak/9f8e16fb10.jpg"
    },
    {
        "id": "119",
        "name": "Traditional Khichdi",
        "description": "One-pot dish of rice and lentils with mild spices",
        "meal_type": "dinner",
        "region": "All India",
        "preparation_time": 30,
        "calories": 300,
        "protein": 12,
        "carbs": 50,
        "fat": 8,
        "tags": ["Healthy", "One-pot", "Light"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["rice", "lentils", "vegetables", "spices", "ghee"],
        "imageUrl": "/Indian Food Images/traditional_khichdi/9f8e16fb10.jpg"
    },
    {
        "id": "120",
        "name": "Aloo Gobi",
        "description": "Potato and cauliflower curry with spices",
        "meal_type": "dinner",
        "region": "North India",
        "preparation_time": 35,
        "calories": 250,
        "protein": 6,
        "carbs": 40,
        "fat": 10,
        "tags": ["One-pot", "Balanced", "Quick"],
        "suitable_for": ["Evening"],
        "ingredients": ["potatoes", "cauliflower", "onions", "tomatoes", "spices"],
        "imageUrl": "/Indian Food Images/aloogobi/9cb1050e35.jpg"
    },
    {
        "id": "121",
        "name": "Pakoras",
        "description": "Deep-fried vegetable fritters with chickpea flour batter",
        "meal_type": "snack",
        "region": "All India",
        "preparation_time": 25,
        "calories": 280,
        "protein": 5,
        "carbs": 25,
        "fat": 18,
        "tags": ["Quick", "Spicy", "Holi_Celebration"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["gram flour", "vegetables", "spices", "oil"],
        "imageUrl": "/Indian Food Images/pakoras/9f8e16fb10.jpg"
    },
    {
        "id": "122",
        "name": "Gajar Ka Halwa",
        "description": "Sweet carrot pudding with milk, nuts, and ghee",
        "meal_type": "dessert",
        "region": "North India",
        "preparation_time": 50,
        "calories": 400,
        "protein": 7,
        "carbs": 55,
        "fat": 20,
        "tags": ["Festive", "Sweet", "Diwali_Special", "Karwa_Chauth_Special"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["carrots", "milk", "sugar", "ghee", "nuts", "cardamom"],
        "imageUrl": "/Indian Food Images/gajar_ka_halwa/9f54710edb.jpg"
    },
    {
        "id": "123",
        "name": "Bhindi Masala",
        "description": "Okra stir-fried with onions, tomatoes, and spices",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 30,
        "calories": 180,
        "protein": 4,
        "carbs": 20,
        "fat": 12,
        "tags": ["Healthy", "Quick", "Light"],
        "suitable_for": ["Afternoon"],
        "ingredients": ["okra", "onions", "tomatoes", "spices", "oil"],
        "imageUrl": "/Indian Food Images/bhindimasala/9f2f3cf0e4.jpg"
    },
    {
        "id": "124",
        "name": "Kathi Roll",
        "description": "Flatbread wrap with spiced fillings and chutneys",
        "meal_type": "snack",
        "region": "East India",
        "preparation_time": 35,
        "calories": 450,
        "protein": 18,
        "carbs": 40,
        "fat": 25,
        "tags": ["Quick", "Spicy", "Protein"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["flatbread", "fillings", "onions", "spices", "chutneys"],
        "imageUrl": "/Indian Food Images/kathiroll/9f8e16fb10.jpg"
    },
    {
        "id": "125",
        "name": "Rogan Josh",
        "description": "Aromatic lamb curry with rich spices",
        "meal_type": "dinner",
        "region": "Kashmir",
        "preparation_time": 90,
        "calories": 580,
        "protein": 35,
        "carbs": 10,
        "fat": 45,
        "tags": ["Spicy", "Protein", "Festive", "Eid_Feast"],
        "suitable_for": ["Evening", "Night"],
        "ingredients": ["lamb", "onions", "tomatoes", "yogurt", "spices"],
        "imageUrl": "/Indian Food Images/roganjosh/9f8e16fb10.jpg"
    },
    {
        "id": "126",
        "name": "Matar Paneer",
        "description": "Cottage cheese and peas in a tomato-based gravy",
        "meal_type": "lunch",
        "region": "North India",
        "preparation_time": 40,
        "calories": 380,
        "protein": 14,
        "carbs": 20,
        "fat": 30,
        "tags": ["Protein", "Balanced", "Quick"],
        "suitable_for": ["Afternoon", "Evening"],
        "ingredients": ["paneer", "peas", "onions", "tomatoes", "spices"],
        "imageUrl": "/Indian Food Images/matarpaneer/9f8e16fb10.jpg"
    },

    {
        "id": "127",
        "name": "Gulab Jamun",
        "description": "Deep-fried milk solids soaked in sugar syrup",
        "meal_type": "dessert",
        "region": "All India",
        "preparation_time": 45,
        "calories": 420,
        "protein": 5,
        "carbs": 70,
        "fat": 15,
        "tags": ["Festive", "Sweet", "Diwali_Special", "Eid_Feast", "Raksha_Bandhan_Sweet"],
        "suitable_for": ["Afternoon", "Evening", "Night"],
        "ingredients": ["milk powder", "flour", "sugar", "cardamom", "saffron", "nuts"],
        "imageUrl": "/Indian Food Images/gulab_jamun/9c70d9a3ff.jpg"
    },
    {
        "id": "128",
        "name": "Kuzhi paniyaram",
        "description": "Sweet rice and lentil balls",
        "meal_type": "dessert",
        "region": "South India",
        "preparation_time": 30,
        "calories": 250,
        "protein": 4,
        "carbs": 35,
        "fat": 10,
        "tags": "Festive,One-pot",
        "suitable_for": "Afternoon;Evening",
        "ingredients": "Black lentils; rice",
        "imageUrl": "/Indian Food Images/kuzhi_paniyaram/9fd36f2a3a.jpg"
    },
    {
        "id": "129",
        "name": "Chana Masala",
        "description": "Spicy chickpea curry",
        "meal_type": "main course",
        "region": "North India",
        "preparation_time": 40,
        "calories": 350,
        "protein": 8,
        "carbs": 40,
        "fat": 15,
        "tags": "Protein,Healthy,Quick,One-pot",
        "suitable_for": "Afternoon;Evening;Night",
        "ingredients": "Chickpeas; onions; garam masala; tomatoes; ginger; garlic",
        "imageUrl": "/Indian Food Images/chana_masala/9ef5280afc.jpg"
    },
    {
        "id": "130",
        "name": "Kofta",
        "description": "Minced meatballs in a thick sauce",
        "meal_type": "main course",
        "region": "North India",
        "preparation_time": 50,
        "calories": 350,
        "protein": 8,
        "carbs": 40,
        "fat": 15,
        "tags": "Protein,Healthy,Quick,One-pot",
        "suitable_for": "Afternoon;Evening;Night",
        "ingredients": "Minced meat; onions; tomatoes; spices; oil",
        "imageUrl": "/Indian Food Images/kofta/9f8e16fb10.jpg"
    }
]

# Festival specific dishes
FESTIVAL_DISHES = {
    "diwali": sorted(list(set([
        "Aloo Tikki", "Anarsa", "Balu shahi", "Balushahi", "Barfi", "Boondi", 
        "Fresh Jalebi", "Gajar Ka Halwa", "Gajar ka halwa", "Gulab Jamun", 
        "Imarti", "Jalebi", "Kachori", "Kaju Katli", "Kaju katli", "Kheer", 
        "Kheer sagar", "Laddu", "Ledikeni", "Malapua", "Mysore Pak", "Pakoras", 
        "Pantua", "Petha", "Phirni", "Rasabali", "Rasgulla", "Samosa", "Sandesh", 
        "Shankarpali", "Sohan Halwa", "Sohan Papdi", "Sohan papdi"
    ]))),
    "holi": sorted(list(set([
        "Boondi", "Chaat", "Dahi Bhalla", "Fresh Jalebi", "Gujiya", "Jalebi", 
        "Kachori", "Lassi", "Malpua", "Obbattu holige", "Pakoras", "Puran Poli", 
        "Samosa", "Shankarpali", "Thandai"
    ]))),
    "navratri": sorted(list(set([
        "Aloo Jeera", "Fruit Chaat", "Kheer", "Kuttu Ki Puri", "Lassi", 
        "Makhana Kheer", "Petha", "Sabudana Khichdi", "Sabudana Vada", 
        "Samak Rice", "Singhare Ka Halwa"
    ]))),
    "eid": sorted(list(set([
        "Biryani", "Double Ka Meetha", "Double ka meetha", "Fresh Jalebi", 
        "Gulab Jamun", "Haleem", "Hyderabadi Biryani", "Jalebi", "Kebabs", 
        "Kheer", "Phirni", "Rogan Josh", "Sheer Khurma", "Sheer korma", "Seviyan"
    ]))),
    "pongal": sorted(list(set([
        "Avial", "Idli Sambar", "Kuzhi paniyaram", "Medu Vada", "Payasam", 
        "Pongal", "Pongal Rice", "Rasam", "Sakkarai Pongal", "Unni Appam", "Vadai"
    ]))),
    "onam": sorted(list(set([
        "Avial", "Erissery", "Idli", "Idli Sambar", "Kalan", "Kootu Curry", "Olan", 
        "Pachadi", "Parippu", "Payasam", "Pulissery", "Rasam", "Sambar", "Thoran", 
        "Unni Appam"
    ]))),
    "durga_puja": sorted(list(set([
        "Chak Hao Kheer", "Cham cham", "Chomchom", "Cholar Dal", "Kheer Kadam", 
        "Kosha Mangsho", "Luchi", "Maach Jhol", "Mishti Doi", "Misti doi", 
        "Pantua", "Pithe", "Rasgulla", "Sandesh"
    ]))),
    "ganesh_chaturthi": sorted(list(set([
        "Besan Ladoo", "Dhondas", "Karanji", "Kesar Peda", "Laddu", "Ladoo", 
        "Modak", "Motichoor Laddu", "Obbattu holige", "Patholi", "Puran Poli", 
        "Sheera", "Ukadiche Modak"
    ]))),
    "bihu": sorted(list(set([
        "Chak Hao Kheer", "Chira", "Curd", "Ghila Pitha", "Jaggery", "Jolpan", 
        "Khar", "Laru", "Masor Tenga", "Narikolor Laru", "Pitha", "Til Pitha"
    ]))),
    "guru_nanak_jayanti": sorted(list(set([
        "Amritsari Kulcha", "Chole Bhature", "Gajar Ka Halwa", "Kada Prasad", 
        "Langar", "Lassi", "Maa Di Dal", "Makki Di Roti", "Phirni", "Pinni", 
        "Sarson Da Saag"
    ]))),
    "chhath_puja": sorted(list(set([
        "Chana Dal", "Kaddu Bhaat", "Kheer", "Malpua", "Puri", "Rasiao Kheer", 
        "Rice Laddoo", "Thekua"
    ]))),
    "janmashtami": sorted(list(set([
        "Dahi Mishri", "Gopalkala", "Kheer", "Makhan Mishri", "Malpua", 
        "Mathura Peda", "Panchamrit", "Panjiri", "Sabudana Kheer"
    ]))),
    "raksha_bandhan": sorted(list(set([
        "Balu shahi", "Balushahi", "Barfi", "Besan Ladoo", "Fresh Jalebi", 
        "Ghevar", "Gulab Jamun", "Jalebi", "Kaju Katli", "Kaju katli", "Kheer", 
        "Laddu", "Ladoo", "Ras Malai", "Ras malai", "Sohan Halwa", "Sohan halwa"
    ]))),
    "karwa_chauth": sorted(list(set([
        "Aloo Sabzi", "Dry Fruits", "Gajar Ka Halwa", "Gajar ka halwa", "Halwa", 
        "Kheer", "Matthi", "Meethi Sevaiyan", "Pheni", "Puri", "Sargi", "Seviyan"
    ]))),
    "baisakhi": sorted(list(set([
        "Amritsari Kulcha", "Chole Bhature", "Fresh Jalebi", "Jalebi", 
        "Kada Prasad", "Lassi", "Meethe Chawal", "Phirni", "Pindi Chole", 
        "Pinni", "Sarson Da Saag", "Makki Di Roti"
    ])))
}

# Apply standardization to create the final dataset
MEAL_DATASET = standardize_meal_dataset(_MEAL_DATASET_RAW)

# Function to get meal suggestions based on time of day
def get_meals_by_time(time_of_day, limit=10):
    """Get meal suggestions based on time of day"""
    suitable_meals = []
    for meal in MEAL_DATASET:
        suitable_for = meal.get("suitable_for", [])
        # Now we can just check if time_of_day is in the list
        if time_of_day in suitable_for:
            suitable_meals.append(meal)
    return suitable_meals[:limit]

# Function to get meal suggestions based on tags
def get_meals_by_tags(tags, limit=10):
    """Get meal suggestions based on tags"""
    suitable_meals = []
    for meal in MEAL_DATASET:
        meal_tags = meal.get("tags", [])
        # Now we can just check if any tag is in the list
        if any(tag in meal_tags for tag in tags):
            suitable_meals.append(meal)
    return suitable_meals[:limit]

# Function to get festival-specific dishes
def get_festival_dishes(festival_id):
    """Get dishes for a specific festival"""
    if festival_id.lower() in FESTIVAL_DISHES:
        dishes = FESTIVAL_DISHES[festival_id.lower()]
        # Use case-insensitive matching for dish names
        return [meal for meal in MEAL_DATASET if any(dish.lower() in meal["name"].lower() for dish in dishes)]
    return []